---
rhcos_version: 4.6.8
vm_import_bucket_name: rhcos-vmdk-import
cloud_region: us-gov-west-1
cloud_key_id_special: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
cloud_key_secret_special: "{{ lookup('env', 'AWS_SECRET_KEY') }}"